services:
  robust:
    build: .
    volumes:
      - "./:/workspace/"
    command: "python experiments/robust_run.py"

  stochastic:
    build: .
    volumes:
      - "./:/workspace/"
    command: "python experiments/stochastic_run.py"
